(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>window.SafeOSSecurity?.esc?.(v)??String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Date().toISOString().slice(0,10);
const uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,6)}`.toUpperCase();
const load=(k,f=[])=>{try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}};
const save=(k,v)=>{localStorage.setItem(k,JSON.stringify(v));window.SafeOSStorage?.mirror?.(k,v);window.SafeOSSecurity?.log?.('save',k);window.dispatchEvent(new Event('safeos-data-changed'));};
const clean=v=>window.SafeOSStorage?.clean?.(v)||String(v||'SafeOS').replace(/\W+/g,'_');
const company=()=>load('hseqt2-company',{});
const statusClass=s=>/closed|completed|compliant|valid|active|satisfactory|available|approved/i.test(s)?'good':/critical|expired|overdue|non-compliant|unsafe|suspended|failed/i.test(s)?'bad':'warn';

const campSchemas={
 master:{label:'Camp Profile & Capacity',icon:'🏘️',fields:[['campName','Camp name','text'],['campCode','Camp code','text'],['location','Location','text'],['landlord','Landlord / operator','text'],['manager','Camp manager','text'],['campBoss','Camp boss','text'],['capacity','Approved capacity','number'],['occupancy','Current occupancy','number'],['rooms','Rooms','number'],['approvalExpiry','Authority approval expiry','date'],['status','Status','select','Active|Under Review|Suspended|Closed'],['notes','Scope / notes','textarea']]},
 daily:{label:'Daily Camp Boss Check',icon:'☀️',fields:[['camp','Camp','text'],['date','Inspection date','date'],['shift','Shift','select','Morning|Evening|Night'],['inspector','Camp boss / inspector','text'],['housekeeping','Rooms and common areas','select','Compliant|Partial|Non-compliant'],['water','Drinking water available','select','Compliant|Partial|Non-compliant'],['toilets','Toilets and showers','select','Compliant|Partial|Non-compliant'],['kitchen','Kitchen and dining','select','Compliant|Partial|Non-compliant'],['fire','Fire exits and equipment','select','Compliant|Partial|Non-compliant'],['waste','Waste removal','select','Compliant|Partial|Non-compliant'],['finding','Key finding','textarea'],['action','Immediate action','textarea'],['status','Status','select','Satisfactory|Action Required|Critical']]},
 occupancy:{label:'Room & Occupancy Register',icon:'🛏️',fields:[['camp','Camp','text'],['building','Building / block','text'],['room','Room number','text'],['approved','Approved beds','number'],['occupied','Occupied beds','number'],['nationality','Occupant group / nationality','text'],['supervisor','Room representative','text'],['acCondition','AC / ventilation','select','Good|Needs Repair|Out of Service'],['electrical','Electrical condition','select','Safe|Needs Attention|Unsafe'],['cleanliness','Cleanliness','select','Good|Fair|Poor'],['lastInspection','Last inspection','date'],['status','Status','select','Compliant|Action Required|Overcrowded']]},
 water:{label:'Water, Hygiene & Food Safety',icon:'💧',fields:[['camp','Camp','text'],['recordType','Record type','select','Drinking Water Test|Tank Cleaning|Kitchen Inspection|Food Handler Check|Pest Control|Cleaning Schedule|Waste / Sewage'],['serviceDate','Service / test date','date'],['nextDue','Next due date','date'],['provider','Service provider / laboratory','text'],['reference','Certificate / report reference','text'],['result','Result','select','Satisfactory|Conditional|Unsatisfactory|Pending'],['temperature','Temperature / measurement','text'],['finding','Finding / remarks','textarea'],['action','Required action','textarea'],['owner','Responsible person','text'],['status','Status','select','Compliant|Open|Overdue|Closed']]},
 safety:{label:'Fire, LPG & Electrical',icon:'🔥',fields:[['camp','Camp','text'],['category','Category','select','Fire Alarm|Fire Extinguishers|Emergency Lighting|Exit Routes|LPG Installation|Gas Detection|Electrical DB|Portable Appliances|Generator|Emergency Drill'],['assetArea','Asset / area','text'],['inspectionDate','Inspection date','date'],['expiryDue','Certificate / service due','date'],['contractor','Contractor / competent person','text'],['condition','Condition','select','Good|Defect|Critical Defect|Out of Service'],['finding','Finding','textarea'],['action','Corrective action','textarea'],['responsible','Responsible person','text'],['status','Status','select','Compliant|Open|Overdue|Closed']]},
 complaints:{label:'Complaints, Welfare & Maintenance',icon:'🤝',fields:[['camp','Camp','text'],['reference','Request / complaint reference','text'],['date','Date raised','date'],['category','Category','select','Accommodation|Water|Food|Sanitation|Maintenance|Transport|Payroll / HR|Medical|Harassment|Suggestion|Other'],['raisedBy','Raised by / anonymous','text'],['channel','Channel','select','QR Report|Camp Boss|HSE Visit|Worker Committee|Phone|Email|Walk-in'],['description','Description','textarea'],['priority','Priority','select','Low|Medium|High|Critical'],['assignedTo','Assigned to','text'],['targetDate','Target date','date'],['resolution','Resolution / response','textarea'],['status','Status','select','New|Under Review|In Progress|Resolved|Closed|Overdue']]},
 behaviour:{label:'Behaviour, Security & Worker Support',icon:'🛡️',fields:[['camp','Camp','text'],['reference','Case reference','text'],['date','Date','date'],['caseType','Case type','select','Alcohol Suspected|Physical Altercation|Threat / Harassment|Security Breach|Medical / Mental Wellbeing|Missing Worker|Property Damage|Rule Violation|Positive Intervention'],['persons','Persons involved','text'],['risk','Immediate risk','select','Low|Medium|High|Emergency'],['immediateAction','Immediate safe action','textarea'],['referral','Referral / coordination','select','Camp Management|HSE|HR|Security|Police|Ambulance / Clinic|Landlord|Other'],['investigation','Investigation summary','textarea'],['followUp','Follow-up action','textarea'],['owner','Case owner','text'],['status','Status','select','Open|Under Investigation|Referred|Monitoring|Closed']]},
 emergency:{label:'Emergency, Drills & Readiness',icon:'🚨',fields:[['camp','Camp','text'],['reference','Drill / event reference','text'],['type','Type','select','Fire Evacuation|Medical Emergency|Gas Leak|Food Poisoning|Security Incident|Severe Weather|Utility Failure'],['date','Date','date'],['participants','Participants','number'],['responseTime','Response time (minutes)','number'],['headcount','Headcount result','select','Complete|Delayed|Mismatch'],['alarm','Alarm / communication','select','Effective|Partial|Failed'],['score','Score %','number'],['findings','Findings','textarea'],['actions','Improvement actions','textarea'],['nextDue','Next drill / review due','date'],['status','Status','select','Satisfactory|Action Required|Critical']]},
 documents:{label:'Camp Documents & Expiry',icon:'📄',fields:[['camp','Camp','text'],['documentType','Document type','select','Tenancy / Lease|Municipality Approval|Civil Defence Approval|Pest Control Contract|Water Test Report|Tank Cleaning Certificate|LPG Certificate|Fire System Contract|Cleaning Contract|Food Permit|Insurance|Emergency Plan'],['reference','Reference','text'],['issuer','Issuer / authority','text'],['issueDate','Issue date','date'],['expiryDate','Expiry / review date','date'],['owner','Document owner','text'],['evidence','File / link reference','text'],['status','Status','select','Valid|Due Soon|Expired|Under Renewal|Not Available'],['notes','Notes','textarea']]}
};
const transportSchemas={
 fleet:{label:'Fleet & Machinery Register',icon:'🚛',fields:[['assetId','Fleet / asset ID','text'],['category','Category','select','Light Vehicle|Heavy Vehicle|Bus|Truck|Trailer|Excavator|Loader|Roller|Grader|Crane|Forklift|Plant / Machinery|Supplier Vehicle'],['makeModel','Make / model','text'],['plateSerial','Plate / serial number','text'],['ownership','Ownership','select','Company|Hired|Supplier|Subcontractor'],['supplier','Supplier / contractor','text'],['project','Assigned project / site','text'],['operator','Assigned driver / operator','text'],['registrationDue','Registration due','date'],['insuranceDue','Insurance due','date'],['inspectionDue','Inspection / certification due','date'],['status','Status','select','In Service|Standby|Maintenance|Quarantined|Out of Service']]},
 drivers:{label:'Drivers & Operators',icon:'🪪',fields:[['employeeId','Employee / external ID','text'],['name','Driver / operator name','text'],['employer','Employer / contractor','text'],['role','Role','select','Light Vehicle Driver|Heavy Vehicle Driver|Bus Driver|Equipment Operator|Banksman|Transport Supervisor|Mechanic'],['mobile','Mobile','text'],['licenceClass','Licence / permit class','text'],['licenceExpiry','Licence expiry','date'],['medicalExpiry','Medical fitness expiry','date'],['defensiveExpiry','Defensive driving expiry','date'],['competencyExpiry','Equipment competency expiry','date'],['violations','Open violations / concerns','text'],['status','Status','select','Authorized|Restricted|Suspended|Expired|On Leave']]},
 journey:{label:'Journey & Fatigue Management',icon:'🗺️',fields:[['reference','Journey reference','text'],['date','Journey date','date'],['vehicle','Vehicle / asset','text'],['driver','Driver','text'],['origin','Origin','text'],['destination','Destination','text'],['purpose','Purpose / load','text'],['departure','Departure time','time'],['expectedReturn','Expected return','time'],['routeRisk','Route risk','select','Low|Medium|High|Critical'],['restCheck','Rest / fatigue check','select','Fit|Concern|Not Verified'],['tracker','GPS / communication','select','Active|Limited|Unavailable'],['approval','Approved by','text'],['status','Status','select','Planned|In Transit|Completed|Delayed|Cancelled|Emergency']]},
 inspection:{label:'Daily Vehicle / Machinery Inspection',icon:'✅',fields:[['reference','Inspection reference','text'],['date','Inspection date','date'],['asset','Vehicle / machinery','text'],['driver','Driver / operator','text'],['project','Project / location','text'],['brakes','Brakes / steering','select','Pass|Defect|Critical'],['tyres','Tyres / tracks','select','Pass|Defect|Critical'],['lights','Lights / alarms / beacon','select','Pass|Defect|Critical'],['safety','Seat belt / guards / extinguisher','select','Pass|Defect|Critical'],['leaks','Leaks / environmental condition','select','Pass|Defect|Critical'],['documents','Documents / permits','select','Pass|Defect|Critical'],['finding','Finding','textarea'],['action','Action taken','textarea'],['status','Status','select','Fit for Use|Conditional|Quarantined']]},
 maintenance:{label:'Maintenance & Workshop',icon:'🔧',fields:[['workOrder','Work order','text'],['asset','Vehicle / machinery','text'],['dateReported','Date reported','date'],['defect','Defect / service required','textarea'],['risk','Operational risk','select','Low|Medium|High|Critical'],['workshop','Workshop / service provider','text'],['plannedDate','Planned date','date'],['completedDate','Completion date','date'],['parts','Parts / cost notes','text'],['verification','Post-maintenance verification','textarea'],['verifiedBy','Verified by','text'],['nextService','Next service due','date'],['status','Status','select','Open|Scheduled|In Progress|Completed|Awaiting Parts|Quarantined']]},
 contractors:{label:'Suppliers & Contractors',icon:'🏢',fields:[['company','Supplier / contractor','text'],['service','Service / scope','select','Vehicle Hire|Machinery Hire|Transport Service|Fuel Supply|Tyre Service|Workshop|Recovery|Waste Transport|Material Delivery|Manpower'],['contact','Contact person / phone','text'],['contractRef','Contract / PO reference','text'],['prequalification','HSE prequalification','select','Approved|Conditional|Pending|Rejected'],['insuranceDue','Insurance expiry','date'],['tradeDue','Trade licence expiry','date'],['operatorDocs','Driver / operator files','select','Complete|Partial|Missing'],['fleetDocs','Fleet documents','select','Complete|Partial|Missing'],['performance','Performance rating %','number'],['findings','Open findings','textarea'],['status','Status','select','Active|On Hold|Suspended|Expired|Closed']]},
 incidents:{label:'Transport Incidents & Violations',icon:'⚠️',fields:[['reference','Incident / violation reference','text'],['date','Date and time','datetime-local'],['type','Type','select','Road Traffic Incident|Near Miss|Vehicle Damage|Machinery Incident|Load Shift|Spill / Leak|Speeding|Seat Belt Violation|Mobile Phone Use|Fatigue Concern|Unauthorized Driver|Supplier Incident'],['asset','Vehicle / machinery','text'],['driver','Driver / operator','text'],['location','Location','text'],['severity','Potential severity','select','Low|Medium|High|Critical'],['description','Description','textarea'],['immediate','Immediate actions','textarea'],['cause','Cause / contributing factors','textarea'],['action','Corrective action','textarea'],['responsible','Responsible person','text'],['status','Status','select','New|Under Investigation|Action Open|Closed']]},
 activities:{label:'Transport HSE Activities',icon:'📋',fields:[['reference','Activity reference','text'],['date','Date','date'],['activity','Activity','select','Driver Induction|Defensive Driving Training|Toolbox Talk|Route Risk Assessment|Speed Monitoring|Seat Belt Check|Fatigue Campaign|Vehicle Audit|Contractor Audit|Workshop Inspection|Emergency Drill|Fuel / Spill Inspection|Loading / Unloading Observation'],['project','Project / location','text'],['owner','Activity owner','text'],['participants','Participants / units checked','number'],['target','Target / planned','number'],['result','Result / score %','number'],['finding','Finding / learning','textarea'],['followUp','Follow-up action','textarea'],['due','Action due date','date'],['status','Status','select','Completed|Action Required|In Progress|Planned']]}
};
const modules={camps:{key:'safeos4-camps',title:'Labour Camps',subtitle:'Accommodation, welfare, hygiene, safety, worker support and compliance',schemas:campSchemas,folder:'18_Labour_Camps'},transport:{key:'safeos4-transport',title:'Transport & Fleet',subtitle:'Fleet, drivers, journeys, machinery, suppliers, contractors and transport HSE',schemas:transportSchemas,folder:'19_Transport'}};
const samples={
 camps:[
 {type:'master',id:'CAMP-DEMO-01',campName:'Al Warsan Workforce Camp',campCode:'CAMP-WSN-01',location:'Dubai',landlord:'Demo Accommodation LLC',manager:'M. Kareem',campBoss:'R. Ahmed',capacity:780,occupancy:742,rooms:126,approvalExpiry:'2027-02-15',status:'Active',notes:'Sample profile for demonstration.'},
 {type:'master',id:'CAMP-DEMO-02',campName:'Al Ain Project Camp',campCode:'CAMP-AAN-02',location:'Al Ain',landlord:'Demo Property Services',manager:'S. Khan',campBoss:'A. Rahman',capacity:420,occupancy:398,rooms:72,approvalExpiry:'2026-11-30',status:'Under Review',notes:'Approval renewal tracking sample.'},
 {type:'daily',id:'CAMP-DAILY-01',camp:'Al Warsan Workforce Camp',date:today(),shift:'Morning',inspector:'Camp Boss',housekeeping:'Compliant',water:'Compliant',toilets:'Partial',kitchen:'Compliant',fire:'Compliant',waste:'Compliant',finding:'Two shower taps leaking in Block B.',action:'Maintenance request raised.',status:'Action Required'},
 {type:'occupancy',id:'CAMP-ROOM-01',camp:'Al Warsan Workforce Camp',building:'Block A',room:'A-108',approved:6,occupied:6,nationality:'Mixed workforce',supervisor:'Room representative',acCondition:'Good',electrical:'Safe',cleanliness:'Good',lastInspection:today(),status:'Compliant'},
 {type:'water',id:'CAMP-WATER-01',camp:'Al Warsan Workforce Camp',recordType:'Drinking Water Test',serviceDate:'2026-07-10',nextDue:'2027-01-10',provider:'Accredited Laboratory (sample)',reference:'WTR-2026-0710',result:'Satisfactory',temperature:'Within sampling requirement',finding:'No adverse observation.',action:'Continue scheduled monitoring.',owner:'Camp HSE',status:'Compliant'},
 {type:'safety',id:'CAMP-FIRE-01',camp:'Al Ain Project Camp',category:'Fire Extinguishers',assetArea:'Dining and kitchen areas',inspectionDate:'2026-07-18',expiryDue:'2027-01-18',contractor:'Competent fire contractor',condition:'Defect',finding:'One extinguisher access obstructed.',action:'Clear access and brief kitchen team.',responsible:'Camp Boss',status:'Open'},
 {type:'complaints',id:'CAMP-COMP-01',camp:'Al Warsan Workforce Camp',reference:'CMP-2026-001',date:'2026-07-20',category:'Maintenance',raisedBy:'Worker committee',channel:'Camp Boss',description:'Hot-water supply intermittent in Block C.',priority:'Medium',assignedTo:'Landlord maintenance',targetDate:'2026-07-25',resolution:'Technician visit scheduled.',status:'In Progress'},
 {type:'behaviour',id:'CAMP-BEH-01',camp:'Al Ain Project Camp',reference:'BEH-2026-003',date:'2026-07-19',caseType:'Positive Intervention',persons:'Camp security and camp boss',risk:'Low',immediateAction:'De-escalated a verbal disagreement before escalation.',referral:'Camp Management',investigation:'No physical contact or injury.',followUp:'Behaviour expectations reinforced at toolbox talk.',owner:'Camp Manager',status:'Closed'},
 {type:'emergency',id:'CAMP-DRILL-01',camp:'Al Warsan Workforce Camp',reference:'DRL-2026-04',type:'Fire Evacuation',date:'2026-07-16',participants:704,responseTime:6.8,headcount:'Complete',alarm:'Effective',score:88,findings:'One assembly-point marshal arrived late.',actions:'Assign trained backup marshal.',nextDue:'2026-10-16',status:'Action Required'},
 {type:'documents',id:'CAMP-DOC-01',camp:'Al Warsan Workforce Camp',documentType:'Water Test Report',reference:'WTR-2026-0710',issuer:'Accredited Laboratory (sample)',issueDate:'2026-07-12',expiryDate:'2027-01-10',owner:'Camp HSE',evidence:'Local SafeOS attachment folder',status:'Valid',notes:'Sample record; replace with actual authority/lab document.'}
 ],
 transport:[
 {type:'fleet',id:'FLT-DEMO-01',assetId:'FLT-TRK-014',category:'Truck',makeModel:'Demo 6x4 Tipper',plateSerial:'DUBAI-00000',ownership:'Company',supplier:'',project:'Road Project A',operator:'Driver 1042',registrationDue:'2027-02-10',insuranceDue:'2027-01-25',inspectionDue:'2026-08-10',status:'In Service'},
 {type:'fleet',id:'FLT-DEMO-02',assetId:'PLT-EXC-007',category:'Excavator',makeModel:'Demo 35T Excavator',plateSerial:'SERIAL-DEMO-007',ownership:'Hired',supplier:'Demo Plant Hire LLC',project:'Infrastructure Site B',operator:'Operator 208',registrationDue:'',insuranceDue:'2026-12-01',inspectionDue:'2026-08-02',status:'Maintenance'},
 {type:'drivers',id:'DRV-DEMO-01',employeeId:'EMP-1042',name:'Sample Driver A',employer:'Company',role:'Heavy Vehicle Driver',mobile:'0500000000',licenceClass:'UAE Heavy Vehicle',licenceExpiry:'2027-03-12',medicalExpiry:'2027-01-15',defensiveExpiry:'2026-12-20',competencyExpiry:'',violations:'None open',status:'Authorized'},
 {type:'drivers',id:'DRV-DEMO-02',employeeId:'EXT-208',name:'Sample Operator B',employer:'Demo Plant Hire LLC',role:'Equipment Operator',mobile:'0500000001',licenceClass:'Operator permit',licenceExpiry:'2026-10-20',medicalExpiry:'2026-09-30',defensiveExpiry:'',competencyExpiry:'2026-08-15',violations:'Competency renewal due soon',status:'Restricted'},
 {type:'journey',id:'JRN-DEMO-01',reference:'JMP-2026-071',date:today(),vehicle:'FLT-TRK-014',driver:'Sample Driver A',origin:'Main yard',destination:'Road Project A',purpose:'Aggregate delivery',departure:'06:00',expectedReturn:'13:30',routeRisk:'Medium',restCheck:'Fit',tracker:'Active',approval:'Transport Supervisor',status:'Completed'},
 {type:'inspection',id:'VINSP-DEMO-01',reference:'DVI-2026-0723',date:today(),asset:'FLT-TRK-014',driver:'Sample Driver A',project:'Road Project A',brakes:'Pass',tyres:'Pass',lights:'Defect',safety:'Pass',leaks:'Pass',documents:'Pass',finding:'Left reverse lamp intermittent.',action:'Repair before night operation.',status:'Conditional'},
 {type:'maintenance',id:'MNT-DEMO-01',workOrder:'WO-2026-188',asset:'PLT-EXC-007',dateReported:'2026-07-22',defect:'Hydraulic hose seepage identified during pre-use inspection.',risk:'High',workshop:'Site workshop',plannedDate:'2026-07-23',completedDate:'',parts:'Replacement hose ordered',verification:'Pending pressure test',verifiedBy:'',nextService:'2026-09-01',status:'In Progress'},
 {type:'contractors',id:'SUP-DEMO-01',company:'Demo Plant Hire LLC',service:'Machinery Hire',contact:'Fleet coordinator / 0500000002',contractRef:'PO-DEMO-884',prequalification:'Conditional',insuranceDue:'2026-12-01',tradeDue:'2027-01-10',operatorDocs:'Partial',fleetDocs:'Complete',performance:82,findings:'One operator competency renewal due.',status:'Active'},
 {type:'incidents',id:'TRN-INC-DEMO-01',reference:'TRN-NM-2026-005',date:'2026-07-21T09:20',type:'Near Miss',asset:'FLT-TRK-014',driver:'Sample Driver A',location:'Site haul road',severity:'High',description:'Pedestrian entered haul route near reversing truck.',immediate:'Stopped movement and isolated crossing.',cause:'Temporary walkway barrier displaced.',action:'Reinstate barrier, add banksman and brief teams.',responsible:'Site Logistics Manager',status:'Action Open'},
 {type:'activities',id:'TRN-ACT-DEMO-01',reference:'TRN-HSE-2026-19',date:'2026-07-20',activity:'Seat Belt Check',project:'Main yard',owner:'Transport HSE',participants:38,target:40,result:95,finding:'Two passenger seat belts were difficult to latch.',followUp:'Vehicles sent for buckle inspection.',due:'2026-07-24',status:'Action Required'}
 ]
};
function inputHtml(name,label,type,opts){const id=`ops-${name}`;if(type==='textarea')return `<label>${esc(label)}<textarea id="${id}" rows="3"></textarea></label>`;if(type==='select')return `<label>${esc(label)}<select id="${id}">${String(opts||'').split('|').map(x=>`<option>${esc(x)}</option>`).join('')}</select></label>`;return `<label>${esc(label)}<input id="${id}" type="${type||'text'}"></label>`;}
function installNav(){const settings=$('.nav-link[data-nav="settings"]');for(const [key,mod] of Object.entries(modules)){if($(`.nav-link[data-nav="${key}"]`))continue;const b=document.createElement('button');b.className='nav-link';b.dataset.nav=key;b.innerHTML=`${key==='camps'?'🏘️':'🚛'} <span>${mod.title}</span>`;settings?.before(b);b.addEventListener('click',()=>showPage(key,true));}}
function moduleHtml(key,mod){return `<section class="page specialist-page" id="page-${key}">
<div class="page-head"><div><span class="eyebrow">SPECIALIST OPERATIONS</span><h1>${mod.title}</h1><p>${mod.subtitle}</p></div><div class="head-actions"><button class="secondary" data-ops-print="${key}">🖨️ PDF Report</button><button class="secondary" data-ops-csv="${key}">⬇️ CSV</button></div></div>
<div class="ops-kpis" id="${key}Kpis"></div>
<div class="panel ops-toolbar"><div class="ops-tabs" id="${key}Tabs"></div><div class="toolbar-row"><input id="${key}Search" placeholder="Search records"><select id="${key}Status"><option value="">All statuses</option><option>Open</option><option>Closed</option><option>Compliant</option><option>Action Required</option><option>Critical</option><option>Active</option><option>Expired</option></select><button class="primary" data-ops-new="${key}">＋ New record</button></div></div>
<div class="two-col ops-layout"><section class="panel"><h2 id="${key}FormTitle">Add record</h2><input type="hidden" id="${key}EditId"><div class="form-grid" id="${key}Form"></div><div class="form-actions"><button class="primary" data-ops-save="${key}">Save record</button><button class="secondary" data-ops-cancel="${key}">Clear</button></div></section><section class="panel"><div class="table-wrap"><table><thead id="${key}Head"></thead><tbody id="${key}Body"></tbody></table></div></section></div>
</section>`;}
function installPages(){const settings=$('#page-settings');for(const [k,m] of Object.entries(modules)){if($('#page-'+k))continue;settings?.insertAdjacentHTML('beforebegin',moduleHtml(k,m));const tabs=$('#'+k+'Tabs');Object.entries(m.schemas).forEach(([type,s],i)=>{const b=document.createElement('button');b.className='subtab '+(i===0?'active':'');b.dataset.type=type;b.innerHTML=`${s.icon} ${s.label}`;tabs.appendChild(b);b.addEventListener('click',()=>{state[k].type=type;$$('.subtab',tabs).forEach(x=>x.classList.toggle('active',x===b));renderForm(k);renderTable(k);});});}}
const state={camps:{type:'master'},transport:{type:'fleet'}};
function schema(k){return modules[k].schemas[state[k].type];}
function rows(k){return load(modules[k].key,[]);}
function renderForm(k,record={}){const s=schema(k);$(`#${k}FormTitle`).textContent=record.id?`Edit ${s.label}`:`Add ${s.label}`;$(`#${k}EditId`).value=record.id||'';$(`#${k}Form`).innerHTML=s.fields.map(f=>inputHtml(...f)).join('');for(const [name,,type] of s.fields){const el=$(`#ops-${name}`);if(!el)continue;el.value=record[name]??(type==='date'?today():'');}}
function getRecord(k){const s=schema(k),obj={id:$(`#${k}EditId`).value||uid(k==='camps'?'CAMP':'TRN'),type:state[k].type,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};for(const [name,,type] of s.fields){let v=$(`#ops-${name}`)?.value??'';if(type==='number')v=Number(v)||0;obj[name]=v;}return obj;}
function saveRecord(k){const r=getRecord(k),all=rows(k),idx=all.findIndex(x=>x.id===r.id);if(idx>=0){r.createdAt=all[idx].createdAt;all[idx]=r;}else all.unshift(r);save(modules[k].key,all);renderForm(k);renderTable(k);renderKpis(k);notify('Record saved to '+modules[k].title);}
function valueDisplay(v){if(v===null||v===undefined||v==='')return '—';return esc(v);}
function renderTable(k){const s=schema(k),q=($(`#${k}Search`)?.value||'').toLowerCase(),status=$(`#${k}Status`)?.value||'';let all=rows(k).filter(r=>r.type===state[k].type);all=all.filter(r=>(!q||JSON.stringify(r).toLowerCase().includes(q))&&(!status||Object.values(r).includes(status)));const cols=s.fields.slice(0,5);$(`#${k}Head`).innerHTML=`<tr><th>#</th>${cols.map(f=>`<th>${esc(f[1])}</th>`).join('')}<th>Actions</th></tr>`;$(`#${k}Body`).innerHTML=all.length?all.map((r,i)=>`<tr><td>${i+1}</td>${cols.map(f=>`<td>${f[0]==='status'?`<span class="status-badge ${statusClass(r[f[0]])}">${valueDisplay(r[f[0]])}</span>`:valueDisplay(r[f[0]])}</td>`).join('')}<td><div class="table-actions"><button class="mini-btn" data-ops-edit="${k}" data-id="${esc(r.id)}">Edit</button><button class="mini-btn danger-mini" data-ops-delete="${k}" data-id="${esc(r.id)}">Delete</button></div></td></tr>`).join(''):`<tr><td colspan="${cols.length+2}">No records in this register.</td></tr>`;}
function renderKpis(k){const all=rows(k),due=all.filter(r=>{const d=r.expiryDate||r.nextDue||r.inspectionDue||r.targetDate||r.due||r.approvalExpiry;if(!d)return false;const days=(new Date(d)-new Date(today()))/86400000;return days>=0&&days<=30}).length,expired=all.filter(r=>Object.values(r).some(v=>typeof v==='string'&&/expired|overdue|critical|unsafe|non-compliant/i.test(v))).length;const groups=new Set(all.map(r=>r.type)).size;$(`#${k}Kpis`).innerHTML=`<div class="kpi-card"><span>Total records</span><strong>${all.length}</strong></div><div class="kpi-card"><span>Registers in use</span><strong>${groups}</strong></div><div class="kpi-card"><span>Due within 30 days</span><strong>${due}</strong></div><div class="kpi-card"><span>Priority attention</span><strong>${expired}</strong></div>`;}
function edit(k,id){const r=rows(k).find(x=>x.id===id);if(!r)return;state[k].type=r.type;const tabs=$(`#${k}Tabs`);$$('.subtab',tabs).forEach(b=>b.classList.toggle('active',b.dataset.type===r.type));renderForm(k,r);renderTable(k);window.scrollTo({top:$(`#page-${k}`).offsetTop,behavior:'smooth'});}
function del(k,id){if(!confirm('Delete this record?'))return;save(modules[k].key,rows(k).filter(x=>x.id!==id));renderTable(k);renderKpis(k);}
function csv(k){const all=rows(k),headers=['Register','ID','Created','Updated','Data'];const lines=[headers,...all.map(r=>[modules[k].schemas[r.type]?.label||r.type,r.id,r.createdAt,r.updatedAt,JSON.stringify(r)])];const text='\ufeff'+lines.map(row=>row.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\r\n');window.SafeOSStorage?.saveExport?.(modules[k].folder,`SafeOS_${clean(modules[k].title)}_Register_${today()}.csv`,new Blob([text],{type:'text/csv;charset=utf-8'}));}
function setupPrint(title,subtitle,reference){const c=company();$('#printCompanyName').textContent=c.name||'Company / Organisation';$('#printCompanyAddress').textContent=c.address||'';$('#printDocRef').textContent=reference;$('#printRevision').textContent=`Rev ${c.revision||'0'}`;$('#printGenerated').textContent=new Date().toLocaleString();$('#printTitle').textContent=title;$('#printSubtitle').textContent=subtitle;$('#printLogo').innerHTML=c.logo?`<img src="${c.logo}" alt="Company logo">`:'';}
function printModule(k){const all=rows(k),mod=modules[k];setupPrint(`${mod.title} Management Report`,mod.subtitle,`${cPrefix()}-${k.toUpperCase()}-${today().replaceAll('-','')}`);$('#printContent').innerHTML=Object.entries(mod.schemas).map(([type,s])=>{const set=all.filter(r=>r.type===type);if(!set.length)return '';const cols=s.fields.slice(0,7);return `<section class="print-section"><h2>${esc(s.label)}</h2><table class="print-table"><thead><tr>${cols.map(f=>`<th>${esc(f[1])}</th>`).join('')}</tr></thead><tbody>${set.map(r=>`<tr>${cols.map(f=>`<td>${valueDisplay(r[f[0]])}</td>`).join('')}</tr>`).join('')}</tbody></table></section>`;}).join('');$('#printArea').dataset.exportName=`${cPrefix()}_${clean(mod.title)}_${today()}.pdf`;$('#printArea').dataset.exportModule=mod.folder;$('#printArea').setAttribute('aria-hidden','false');setTimeout(()=>window.print(),80);}
function cPrefix(){return clean(company().prefix||'HSE').toUpperCase();}
function notify(msg){const t=$('#toast');if(t){t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2500);}}
function showPage(k,push=false){const target=$('#page-'+k);if(!target)return;$$('.page').forEach(p=>p.classList.toggle('active',p===target));$$('.nav-link').forEach(n=>n.classList.toggle('active',n.dataset.nav===k));$('#sidebar')?.classList.remove('open');if(push&&location.hash!=='#'+k)history.pushState({safeosPage:k},'','#'+k);renderKpis(k);renderTable(k);renderForm(k);window.scrollTo(0,0);}
function seedSpecialist(){for(const k of Object.keys(modules)){const existing=rows(k);if(!existing.length)save(modules[k].key,samples[k]);}}
function bind(){document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.opsNew){renderForm(b.dataset.opsNew);return;}if(b.dataset.opsSave){saveRecord(b.dataset.opsSave);return;}if(b.dataset.opsCancel){renderForm(b.dataset.opsCancel);return;}if(b.dataset.opsEdit){edit(b.dataset.opsEdit,b.dataset.id);return;}if(b.dataset.opsDelete){del(b.dataset.opsDelete,b.dataset.id);return;}if(b.dataset.opsCsv){csv(b.dataset.opsCsv);return;}if(b.dataset.opsPrint){printModule(b.dataset.opsPrint);return;}if(b.classList.contains('nav-link')&&modules[b.dataset.nav])showPage(b.dataset.nav,true);});for(const k of Object.keys(modules)){[$(`#${k}Search`),$(`#${k}Status`)].forEach(el=>el?.addEventListener(el.tagName==='INPUT'?'input':'change',()=>renderTable(k)));}}
function seedCore(){const defs={
 'hseqt2-risks':[{id:'RA-SAMPLE-01',ref:'HSE-RA-001',title:'Working at height from mobile scaffold',activity:'Façade installation',location:'Building Project A',date:today(),reviewDate:'2026-10-23',assessor:'Sample HSE Officer',approver:'Project Manager',hazard:'Fall from height and falling objects',affected:'Workers and persons below',harm:'Serious injury or fatality',existing:'Certified scaffold, guardrails, inspection tag, exclusion zone, trained users',initialL:4,initialS:5,initialScore:20,further:'Use tool lanyards and verify scaffold after relocation',hierarchy:'Engineering',owner:'Site Engineer',target:'2026-07-25',residualL:2,residualS:5,residualScore:10,status:'Open',notes:'Sample data.'},{id:'RA-SAMPLE-02',ref:'HSE-RA-002',title:'Diesel refuelling of mobile plant',activity:'Fuel transfer',location:'Plant yard',date:today(),reviewDate:'2026-10-23',assessor:'Transport HSE',approver:'Transport Manager',hazard:'Fire, spill and vehicle movement',affected:'Operator, fuel bowser driver, environment',harm:'Burns, collision, soil contamination',existing:'Engine off, bonding, extinguisher, spill kit, segregated bay',initialL:3,initialS:5,initialScore:15,further:'Install wheel stops and verify emergency shutoff',hierarchy:'Engineering',owner:'Workshop Supervisor',target:'2026-07-30',residualL:1,residualS:5,residualScore:5,status:'In Progress'}],
 'hseqt2-incidents':[{id:'INC-SAMPLE-01',ref:'HSE-INC-001',title:'Pedestrian–vehicle near miss',type:'Near Miss',date:'2026-07-20',time:'09:10',location:'Site access road',reportedBy:'Site Supervisor',severity:'High',status:'Under Investigation',description:'Pedestrian entered a reversing route when a temporary barrier was displaced.',immediate:'Vehicle stopped; route isolated.',causes:'Barrier displaced and no alternate pedestrian route.',actions:'Reinstate segregation and assign banksman.',lessons:'Traffic plans require verification after layout changes.'},{id:'INC-SAMPLE-02',ref:'HSE-INC-002',title:'Minor hand cut during material handling',type:'First Aid Case',date:'2026-07-18',time:'14:30',location:'Warehouse',reportedBy:'Storekeeper',severity:'Low',status:'Closed',description:'Worker contacted sharp banding edge.',immediate:'First aid and task stopped.',causes:'Damaged packaging band exposed.',actions:'Use cutting tool and gloves; reject damaged bundles.',lessons:'Inspect packaging before manual handling.'}],
 'hseqt2-capa':[{id:'CAPA-SAMPLE-01',capaId:'HSE-CAPA-001',source:'Inspection',category:'Fire safety',finding:'Emergency exit partly obstructed.',action:'Remove stored materials and mark no-storage zone.',responsible:'Camp Boss',department:'Labour Camp',opened:'2026-07-20',due:'2026-07-24',priority:'High',status:'In Progress',progress:70,effectiveness:'Not verified'},{id:'CAPA-SAMPLE-02',capaId:'HSE-CAPA-002',source:'Near Miss',category:'Traffic management',finding:'Pedestrian route barrier displaced.',action:'Install fixed barrier and add daily route check.',responsible:'Site Logistics Manager',department:'Construction',opened:'2026-07-21',due:'2026-07-28',priority:'Critical',status:'Open',progress:20,effectiveness:'Not verified'}],
 'safeos3-projects':[{id:'PRJ-SAMPLE-01',projCode:'PRJ-DXB-01',projName:'Road Improvement Project',projClient:'Sample Client',projLocation:'Dubai',projManager:'Project Manager A',projHseLead:'HSE Lead A',projWorkforce:680,projStatus:'Active',projStart:'2026-01-10',projEnd:'2027-04-30',projScope:'Road, utilities and landscaping.'},{id:'PRJ-SAMPLE-02',projCode:'PRJ-AAN-02',projName:'Infrastructure Package',projClient:'Sample Client',projLocation:'Al Ain',projManager:'Project Manager B',projHseLead:'HSE Lead B',projWorkforce:420,projStatus:'Active',projStart:'2026-03-01',projEnd:'2027-08-30',projScope:'Utilities and civil works.'}],
 'safeos3-training':[{id:'TRN-SAMPLE-01',trainingRef:'TRN-2026-101',trainingTopic:'Heat Stress Prevention',trainingType:'Internal Training',trainingSite:'Road Improvement Project',trainingDate:'2026-07-15',trainingExpiry:'2027-07-15',trainingTrainer:'HSE Team',trainingStatus:'Completed',trainingPlanned:55,trainingAttendees:52,trainingResult:'95% pass',trainingEvidence:'Attendance and quiz retained.'},{id:'TRN-SAMPLE-02',trainingRef:'TRN-2026-102',trainingTopic:'Defensive Driving',trainingType:'External Training',trainingSite:'Transport Yard',trainingDate:'2026-06-20',trainingExpiry:'2027-06-20',trainingTrainer:'Approved provider',trainingStatus:'Completed',trainingPlanned:24,trainingAttendees:23,trainingResult:'22 competent; 1 reassessment',trainingEvidence:'Certificates on file.'}],
 'safeos3-assets':[{id:'AST-SAMPLE-01',assetRef:'AST-CRN-001',assetCategory:'Lifting Equipment',assetDescription:'Mobile crane 50T',assetSerial:'CRN-DEMO-01',assetSite:'Road Improvement Project',assetOwner:'Company',assetInspectionDue:'2026-08-20',assetCertificateDue:'2026-09-10',assetStatus:'In Service',assetEvidence:'Inspection certificate attached locally.'},{id:'AST-SAMPLE-02',assetRef:'AST-FE-022',assetCategory:'Fire Safety Equipment',assetDescription:'Dining hall fire extinguishers',assetSerial:'SET-22',assetSite:'Al Warsan Workforce Camp',assetOwner:'Camp Management',assetInspectionDue:'2026-08-01',assetCertificateDue:'2027-01-18',assetStatus:'Active',assetEvidence:'Service sticker and register.'}],
 'safeos3-permits':[{id:'PTW-SAMPLE-01',permitRef:'PTW-HOT-071',permitType:'Hot Work',permitSite:'Infrastructure Package',permitArea:'Workshop zone',permitIssuer:'HSE Officer',permitReceiver:'Workshop Supervisor',permitIssue:'2026-07-23T07:00',permitExpiry:'2026-07-23T17:00',permitStatus:'Closed',permitEvidence:'Gas test and closure check.'},{id:'PTW-SAMPLE-02',permitRef:'PTW-EXC-052',permitType:'Excavation',permitSite:'Road Improvement Project',permitArea:'Chainage 2+400',permitIssuer:'Permit Coordinator',permitReceiver:'Civil Supervisor',permitIssue:'2026-07-23T06:30',permitExpiry:'2026-07-24T18:00',permitStatus:'Active',permitEvidence:'Utility clearance and shoring plan.'}],
 'safeos3-drills':[{id:'DRL-SAMPLE-01',drillRef:'DRL-FIRE-04',drillType:'Fire Evacuation',drillSite:'Al Warsan Workforce Camp',drillDate:'2026-07-16',drillResponse:6.8,drillParticipants:704,drillScore:88,drillStatus:'Action Required',drillFindings:'Backup marshal needed.'},{id:'DRL-SAMPLE-02',drillRef:'DRL-SPILL-02',drillType:'Spill Response',drillSite:'Transport Yard',drillDate:'2026-07-12',drillResponse:4.2,drillParticipants:18,drillScore:92,drillStatus:'Satisfactory',drillFindings:'Improve drain-cover placement speed.'}],
 'safeos3-environment':[{id:'ENV-SAMPLE-01',envMonth:'2026-06',envSite:'Road Improvement Project',envWater:4800,envElectricity:21000,envFuel:34800,envWaste:88,envRecycled:31,envSpills:0},{id:'ENV-SAMPLE-02',envMonth:'2026-07',envSite:'Road Improvement Project',envWater:4650,envElectricity:20500,envFuel:33100,envWaste:84,envRecycled:34,envSpills:1}],
 'safeos3-documents':[{id:'DOC-SAMPLE-01',docRef:'HSE-POL-001',docTitle:'Occupational Health and Safety Policy',docType:'Policy',docRevision:'3',docOwner:'HSE Manager',docIssue:'2026-01-05',docReview:'2027-01-05',docStatus:'Approved',docLocation:'Controlled document library'},{id:'DOC-SAMPLE-02',docRef:'HSE-ERP-002',docTitle:'Labour Camp Emergency Response Plan',docType:'Emergency Plan',docRevision:'2',docOwner:'Camp HSE Engineer',docIssue:'2026-04-12',docReview:'2027-04-12',docStatus:'Approved',docLocation:'Camp and central library'}],
 'safeos3-legal':[{id:'LEG-SAMPLE-01',legalJurisdiction:'UAE / Project requirements',legalAuthority:'Applicable authority / client',legalObligation:'Maintain valid occupational safety and welfare controls applicable to the activity and location.',legalOwner:'HSE Manager',legalEvidence:'Legal register review record',legalReview:'2026-10-01',legalStatus:'Under Review'},{id:'LEG-SAMPLE-02',legalJurisdiction:'Contractual',legalAuthority:'Client specification',legalObligation:'Submit monthly HSE performance and close high-risk findings within agreed periods.',legalOwner:'Project HSE Lead',legalEvidence:'Monthly report and CAPA register',legalReview:'2026-08-01',legalStatus:'Compliant'}],
 'safeos3-performance':[{id:'PERF-SAMPLE-01',perfMonth:'2026-06',perfSite:'Road Improvement Project',perfHours:146000,perfWorkforce:655,perfRecordables:1,perfLti:0,perfLostDays:0,perfNearMisses:18,perfInspections:54,perfTrainings:28,perfObservations:340,perfConsultations:16},{id:'PERF-SAMPLE-02',perfMonth:'2026-07',perfSite:'Road Improvement Project',perfHours:152000,perfWorkforce:680,perfRecordables:0,perfLti:0,perfLostDays:0,perfNearMisses:22,perfInspections:61,perfTrainings:31,perfObservations:402,perfConsultations:19}],
 'safeos3-public-reports':[{id:'PUB-SAMPLE-01',ref:'PUB-2026-001',type:'Unsafe Condition',site:'Road Improvement Project',location:'Pedestrian crossing',severity:'High',description:'Temporary barrier moved after material delivery.',suggestion:'Install a fixed return gate.',reporter:'Anonymous',contact:'',status:'Under Review',createdAt:new Date().toISOString()},{id:'PUB-SAMPLE-02',ref:'PUB-2026-002',type:'Suggestion',site:'Al Warsan Workforce Camp',location:'Dining area',severity:'Low',description:'Add multilingual signs for food-waste segregation.',suggestion:'Use icon-based posters.',reporter:'Worker committee',contact:'',status:'Actioned',createdAt:new Date().toISOString()}]
};for(const [k,v] of Object.entries(defs)){const current=load(k,[]);if(!current.length)save(k,v);}}
function init(){installNav();installPages();seedCore();seedSpecialist();bind();for(const k of Object.keys(modules)){renderForm(k);renderTable(k);renderKpis(k);}const hash=location.hash.slice(1);if(modules[hash])showPage(hash,false);window.SafeOSSpecialist={showPage,renderAll:()=>Object.keys(modules).forEach(k=>{renderTable(k);renderKpis(k);})};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
