(() => {
'use strict';
const DB='safeos-file-handles', STORE='handles', HANDLE_KEY='safeos-root';
const MODULES={
 'hseqt2-company':'01_Company_Profile','safeos3-projects':'02_Projects','hseqt2-risks':'03_Risk_Assessments','hseqt2-jsas':'04_JSA_TRA','hseqt2-incidents':'05_Incidents','hseqt2-inspections':'06_Inspections','hseqt2-capa':'07_CAPA','hseqt2-toolboxes':'08_Toolbox_Talks','safeos3-training':'09_Training','safeos3-assets':'10_Assets_Equipment','safeos3-permits':'11_Permits','safeos3-drills':'12_Emergency','safeos3-environment':'13_Environment','safeos3-documents':'14_Documents','safeos3-legal':'15_Legal_Compliance','safeos3-performance':'16_Performance','safeos3-public-reports':'17_Public_Reports','safeos4-camps':'18_Labour_Camps','safeos4-transport':'19_Transport','safeos4-meetings':'21_Meetings','safeos4-contractors':'22_Contractors','safeos4-hazards':'23_Hazards_Observations'
};
const SUBFOLDERS=['Records','Reports','Attachments'];
let rootHandle=null;
const clean=(v,f='SafeOS')=>String(v||f).normalize('NFKD').replace(/[^\p{L}\p{N}_\- .]+/gu,'').trim().replace(/\s+/g,'_').slice(0,90)||f;
function dbOpen(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>r.result.createObjectStore(STORE);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
async function putHandle(handle){const db=await dbOpen();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(handle,HANDLE_KEY);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);});db.close();}
async function getHandle(){const db=await dbOpen();const value=await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly');const r=tx.objectStore(STORE).get(HANDLE_KEY);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error);});db.close();return value;}
async function permission(handle,write=false){if(!handle) return false;const opts={mode:write?'readwrite':'read'};if((await handle.queryPermission(opts))==='granted') return true;return (await handle.requestPermission(opts))==='granted';}
async function getRoot(){if(rootHandle&&await permission(rootHandle,true)) return rootHandle;try{const h=await getHandle();if(h&&await permission(h,true)){rootHandle=h;return h;}}catch{}return null;}
async function moduleDir(moduleName,sub='Records',create=true){const root=await getRoot();if(!root) return null;const safeos=await root.getDirectoryHandle('SafeOS',{create});const mod=await safeos.getDirectoryHandle(moduleName,{create});return sub?mod.getDirectoryHandle(sub,{create}):mod;}
async function ensureStructure(){const root=await getRoot();if(!root) return false;const safeos=await root.getDirectoryHandle('SafeOS',{create:true});for(const name of [...new Set([...Object.values(MODULES),'20_Backups'])]){const dir=await safeos.getDirectoryHandle(name,{create:true});for(const sub of SUBFOLDERS) await dir.getDirectoryHandle(sub,{create:true});}return true;}
async function connectFolder(){if(!('showDirectoryPicker' in window)) throw new Error('Folder access is not supported by this browser. Use Chrome or Edge, or use download fallback.');rootHandle=await window.showDirectoryPicker({id:'safeos-community',mode:'readwrite',startIn:'documents'});if(!await permission(rootHandle,true)) throw new Error('Folder permission was not granted.');await putHandle(rootHandle);await ensureStructure();localStorage.setItem('safeos4-folder-name',rootHandle.name||'Selected folder');window.dispatchEvent(new CustomEvent('safeos-folder-connected',{detail:{name:rootHandle.name}}));return rootHandle.name;}
async function disconnect(){rootHandle=null;localStorage.removeItem('safeos4-folder-name');try{const db=await dbOpen();const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(HANDLE_KEY);db.close();}catch{}window.dispatchEvent(new Event('safeos-folder-disconnected'));}
async function writeFile(dir,filename,data,type='application/octet-stream'){if(!dir) return false;const h=await dir.getFileHandle(clean(filename),{create:true});const w=await h.createWritable();await w.write(data instanceof Blob?data:new Blob([data],{type}));await w.close();return true;}
function keyModule(key){return MODULES[key]||'20_Backups';}
async function mirror(key,value){try{const dir=await moduleDir(keyModule(key),'Records');if(!dir)return false;const stamp=new Date().toISOString().replace(/[:.]/g,'-');const payload=JSON.stringify({safeosVersion:'4.0.0',storageKey:key,exportedAt:new Date().toISOString(),data:value},null,2);await writeFile(dir,`${clean(key)}_Latest.json`,payload,'application/json');if(Array.isArray(value)&&value.length){const newest=value[0]||value.at(-1);const id=clean(newest.id||newest.ref||newest.code||stamp,'Record');await writeFile(dir,`${id}_${stamp}.json`,JSON.stringify(newest,null,2),'application/json');}return true;}catch(error){console.warn('SafeOS folder mirror failed',error);return false;}}
async function saveExport(moduleName,filename,blob){const moduleFolder=Object.values(MODULES).includes(moduleName)?moduleName:(MODULES[moduleName]||moduleName||'20_Backups');try{const dir=await moduleDir(moduleFolder,'Reports');if(dir){await writeFile(dir,filename,blob,blob.type||'application/octet-stream');return {mode:'folder',filename};}}catch(error){console.warn('Folder export failed; using download',error);}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1500);return {mode:'download',filename};}
async function backupAll(){const snapshot={safeosVersion:'4.0.0',exportedAt:new Date().toISOString(),origin:location.origin,records:{}};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(/^hseqt2-|^safeos[34]-/.test(k)){try{snapshot.records[k]=JSON.parse(localStorage.getItem(k));}catch{snapshot.records[k]=localStorage.getItem(k);}}}const blob=new Blob([JSON.stringify(snapshot,null,2)],{type:'application/json'});return saveExport('20_Backups',`SafeOS_Full_Backup_${new Date().toISOString().slice(0,10)}.json`,blob);}
async function restoreFile(file){const parsed=JSON.parse(await file.text());const records=parsed.records||parsed;for(const [k,v] of Object.entries(records)){if(/^hseqt2-|^safeos[34]-/.test(k))localStorage.setItem(k,JSON.stringify(v));}location.reload();}
async function status(){const supported='showDirectoryPicker' in window;const h=await getRoot();return {supported,connected:!!h,name:h?.name||localStorage.getItem('safeos4-folder-name')||''};}
window.SafeOSStorage={MODULES,clean,connectFolder,disconnect,ensureStructure,mirror,saveExport,backupAll,restoreFile,status,supportsFolderAccess:'showDirectoryPicker' in window,getRoot};
})();
